In [ ]:
# Import Libraries
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load the train and test datasets
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [ ]:
# What are the columns in the dataset?
print("Columns in the training dataset:")
df_train.columns

In [ ]:
# View the first few rows of the DataFrame
#df_train.head()
df_test.head()

In [ ]:
# Data Shape
df_train.shape, df_test.shape

In [ ]:
# We want to merge test and train datasets to do some EDA and feature engineering. We will separate them later on.
# But before that we will add a Survived column to the test dataset and fill it with NaN values. 
# This will help us to identify the test dataset after merging.

df_test['Survived'] = np.nan

df_test.shape
df_test.head()

In [ ]:
# Now we can merge the datasets
df = pd.concat([df_train, df_test], ignore_index=True)
# Now we can check the shape of the merged dataset
df.shape

In [ ]:
df.head()
df.describe()

In [ ]:
# Visualize the Survival Trends

# Let's visualize the count of survivors and non-survivors in the dataset.
import matplotlib.pyplot as plt

sns.countplot(data=df, x='Survived')
plt.title('Survival Count')
plt.xlabel('Survived')
plt.ylabel('Count')
plt.show()

In [ ]:
# Visualize Survival Rate by Gender
sns.countplot(data=df, x='Survived', hue='Sex')
plt.title('Survival Rate by Gender')
plt.xlabel('Survived')
plt.ylabel('Count')
plt.show()

In [ ]:
# Drop columns that are too sparse or irrelevant to the model.
#We are going to drop the following columns:
# - Cabin: This column has a lot of missing values and is not likely to be useful
# - Ticket: This column is not likely to be useful for predicting survival and has many unique values.
# - Name: This column is not likely to be useful for predicting survival and has many unique values.
df.drop(['Cabin', 'Ticket', 'Name'], axis=1, inplace=True)
df.head()

In [19]:
#Next we will check for missing values in the dataset and handle them accordingly. 
# We will use the following strategies to handle missing values:
# - For numerical columns, we will fill the missing values with the median of the column.
# - For categorical columns, we will fill the missing values with the mode of the column.
# Check for missing values
df.isnull().sum()

# Fill missing values for numerical columns with the median one by one
# In this case we have only one numerical column with missing values which is Age, so we will fill it with the median of the Age column.
df['Age'].fillna(df['Age'].median(), inplace=True)


# Fill missing values for categorical columns with the mode
# In this case we have only one categorical column with missing values which is Embarked, so we will fill it with the mode of the Embarked column.
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)


# Check for missing values again to confirm that they have been handled
df.isnull().sum()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18396\607171018.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [22]:
# Now we will check the data types of the columns and convert them to the appropriate data types if necessary.
df.dtypes

# Leave Survived as float because it contains NaN values for the test dataset. 
# We will convert it to int later on after we separate the test dataset from the train dataset.
# Convert Pclass to categorical
df['Pclass'] = df['Pclass'].astype('category')
# Convert Sex to categorical
df['Sex'] = df['Sex'].astype('category')
# Convert Embarked to categorical       
df['Embarked'] = df['Embarked'].astype('category')  
# Check the data types again to confirm that they have been converted
df.dtypes
df.head()

   PassengerId  Survived Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1       0.0      3    male  22.0      1      0   7.2500        S
1            2       1.0      1  female  38.0      1      0  71.2833        C
2            3       1.0      3  female  26.0      0      0   7.9250        S
3            4       1.0      1  female  35.0      1      0  53.1000        S
4            5       0.0      3    male  35.0      0      0   8.0500        S

In [23]:
#We can work save the cleaned and preprocessed dataset to a new CSV file for future use.
df.to_csv('titanic_cleaned.csv', index=False)

In [24]:
# Select the features and target variable for the model
# We will select the following features for our model:  
# - Pclass: Passenger class (1st, 2nd, 3rd)
# - Sex: Gender
# - Age: Age of the passenger
# - SibSp: Number of siblings/spouses aboard the Titanic
# - Parch: Number of parents/children aboard the Titanic
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']
#target = 'Survived'

#Assign the features and target variable to X and y respectively
X = df[features]    
y = df.Survived

In [ ]:
# Split the data back into train and test datasets
X_train = X[:len(df_train)]
X_test = X[len(df_train):]
y_train = y[:len(df_train)]
y_test = y[len(df_train):]

    Pclass     Sex   Age  SibSp  Parch
891      3    male  34.5      0      0
892      3  female  47.0      1      0
893      2    male  62.0      0      0
894      3    male  27.0      0      0
895      3  female  22.0      1      1